### ISSUE TITLE
Alex assumes tab to be size 8

### ISSUE THREAD

**Issue by chamini2** [simonmar/alex#57]
Alex assumes that tab size is `8`, as an example, *gcc* takes tabs as 1 in character size. 

Using tab size `8` also makes the errors like:

    program:2:9

To give addresses that are not real.

I propose we make the size of a tab to be `1`, it's just changing [this line](https://github.com/simonmar/alex/blob/master/src/ParseMonad.hs#L71).

**Comment by simonmar** [comment]
Tabs are size 8 in Haskell, see the Haskell report.

**Comment by osa1** [comment]
How is this related with tab sizes in Haskell report? `\t` is one character but Alex behaves as if it's 8 characters.

**Comment by chamini2** [comment]
Maybe a flag for `--tab-size=NUMBER` that defaults to 8 can be added. I guess that would be done by adding a `State` Monad in the `ParseMonad` module.

**Comment by simonmar** [comment]
Alex adopts the same convention for `.x` files as for Haskell, which is that tab stops are 8 columns apart.  If you don't like this, you don't have to use tabs (in fact, it's better just not to use tabs anyway). 

Now, in the generated lexer (rather than Alex itself) it is arguably wrong to fix the same convention: https://github.com/simonmar/alex/blob/master/templates/wrappers.hs#L151

By all means submit a pull request to change this, I suppose we could have a command line flag, and plumb the tab width through to wrappers.hs using CPP.

**Comment by chamini2** [comment]
Oh... I see my mistake. I thought the line in the `ParseMonad` module I thought it was for the generated lexer. That is what I meant to link. Thank you for clearing that up!

Now, in the line in the wrapper file that you linked, that one should follow the flag's instruction. I'll see to make a pull request with that change!
